import type { Epic, Ticket } from 'sprint-genie-shared'
import type { SubmissionResult } from '../hooks/useSession'

interface ExportOptions {
  epic: Epic
  tickets: Ticket[]
  prefix?: string
  project?: string
  result?: SubmissionResult | null  // if already submitted to Jira, include keys/links
}

/**
 * Generates a Claude Code–compatible task file (.md) from an epic and its tickets.
 * Each ticket becomes a numbered task with type, optional Jira link, and description.
 */
export function buildClaudeCodeMarkdown(opts: ExportOptions): string {
  const { epic, tickets, result } = opts
  const date = new Date().toISOString().slice(0, 10)

  // Map Jira results by summary for lookup (summaries match ticket titles)
  const jiraByTitle = new Map<string, { key: string; url: string }>()
  if (result) {
    for (const t of result.tickets) {
      jiraByTitle.set(t.summary, { key: t.key, url: t.url })
    }
  }

  const epicJira = result
    ? `\n**Jira Epic:** [${result.epicKey}](${result.epicUrl})`
    : ''

  const lines: string[] = []

  // ── Header ────────────────────────────────────────────────────────────────
  lines.push(`# Tasks: ${epic.title}`)
  lines.push('')
  lines.push(`> Generated by Sprint Genie · ${date}`)
  lines.push('')

  // ── Epic overview ─────────────────────────────────────────────────────────
  lines.push('## Epic')
  lines.push('')
  if (epicJira) {
    lines.push(epicJira.trim())
    lines.push('')
  }
  if (epic.description) {
    lines.push(epic.description.trim())
    lines.push('')
  }
  lines.push('---')
  lines.push('')

  // ── Instructions ──────────────────────────────────────────────────────────
  lines.push('## Instructions for Claude Code')
  lines.push('')
  lines.push(
    'Work through each task below in order. For every task:',
  )
  lines.push('')
  lines.push('1. Read the description carefully')
  lines.push('2. Implement the required changes in the codebase')
  lines.push('3. Run relevant tests or verify the change works')
  lines.push('4. Mark the task complete by changing `[ ]` to `[x]`')
  lines.push('')
  lines.push('---')
  lines.push('')

  // ── Tasks ─────────────────────────────────────────────────────────────────
  lines.push('## Tasks')
  lines.push('')

  tickets.forEach((ticket, i) => {
    const num = i + 1
    const jira = jiraByTitle.get(ticket.title)
    const jiraTag = jira ? ` · [${jira.key}](${jira.url})` : ''

    lines.push(`### ${num}. [ ] [${ticket.type}] ${ticket.title}${jiraTag}`)
    lines.push('')

    if (ticket.description && ticket.description.trim()) {
      // Format description paragraphs — preserve line breaks
      const descLines = ticket.description.trim().split('\n')
      for (const dl of descLines) {
        lines.push(dl)
      }
      lines.push('')
    }

    lines.push('---')
    lines.push('')
  })

  return lines.join('\n')
}

/** Triggers a browser download of the markdown string as a .md file. */
export function downloadMarkdown(content: string, epicTitle: string): void {
  const slug = epicTitle
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60)

  const filename = `tasks-${slug || 'sprint'}.md`
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/** Convenience: build and immediately download. */
export function exportForClaudeCode(opts: ExportOptions): string {
  const md = buildClaudeCodeMarkdown(opts)
  downloadMarkdown(md, opts.epic.title)
  return md
}
